
# Postgres config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bookera}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database=postgresql

# Redis configs
spring.data.redis.host = redis
spring.data.redis.port = 6379
spring.cache.type = redis
# Data behavior config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.base-path=/m

management.endpoints.web.exposure.include = *

# App config
server.port=8082
spring.application.name=bookeraV2

# Auth config
app.jwt.secret= ${JWT_SECRET}
# 4 hours
app.jwt.expiration-ms=14400000

# File upload config
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir = uploads


